apiVersion: v1
kind: Service
metadata:
  name: utility-service
  labels:
    app: utility-service
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: grpc
  selector:
    app: utility-service
