apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: clickhouse
  labels:
    app: clickhouse
    component: configuration
data:
  # Main ClickHouse configuration
  config.xml: |
    <clickhouse>
        <!-- Logger configuration -->
        <logger>
            <level>information</level>
            <log>/var/log/clickhouse-server/clickhouse-server.log</log>
            <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
            <size>1000M</size>
            <count>10</count>
        </logger>

        <!-- Listen configuration -->
        <listen_host>0.0.0.0</listen_host>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <interserver_http_port>9009</interserver_http_port>

        <!-- Data directory -->
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        <format_schema_path>/var/lib/clickhouse/format_schemas/</format_schema_path>

        <!-- Memory usage settings for better performance -->
        <max_server_memory_usage_to_ram_ratio>0.8</max_server_memory_usage_to_ram_ratio>
        <max_concurrent_queries>100</max_concurrent_queries>
        <max_connections>4096</max_connections>

        <!-- Performance optimizations for ETL workloads -->
        <merge_tree>
            <max_suspicious_broken_parts>10</max_suspicious_broken_parts>
            <parts_to_delay_insert>150</parts_to_delay_insert>
            <parts_to_throw_insert>300</parts_to_throw_insert>
            <max_parts_in_total>100000</max_parts_in_total>
            <max_compress_block_size>1048576</max_compress_block_size>
            <min_compress_block_size>65536</min_compress_block_size>
        </merge_tree>

        <!-- Compression for better storage efficiency -->
        <compression>
            <case>
                <method>lz4</method>
            </case>
        </compression>

        <!-- Remote servers configuration (for potential clustering) -->
        <remote_servers>
            <clickhouse_cluster>
                <shard>
                    <replica>
                        <host>clickhouse-service</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </clickhouse_cluster>
        </remote_servers>

        <!-- Profiles for different workload types -->
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
                <background_pool_size>16</background_pool_size>
                <background_merges_mutations_concurrency_ratio>2</background_merges_mutations_concurrency_ratio>
            </default>
            
            <etl_batch>
                <max_memory_usage>20000000000</max_memory_usage>
                <max_bytes_before_external_group_by>20000000000</max_bytes_before_external_group_by>
                <max_bytes_before_external_sort>30000000000</max_bytes_before_external_sort>
                <max_insert_block_size>1048576</max_insert_block_size>
                <min_insert_block_size_rows>262144</min_insert_block_size_rows>
            </etl_batch>
        </profiles>

        <!-- Users configuration -->
        <users>
            <!-- Default user (read-only access) -->
            <default>
                <password></password>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
                <access_management>1</access_management>
            </default>
        </users>

        <!-- Quotas -->
        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </clickhouse>

  # Users configuration file
  users.xml: |
    <clickhouse>
        <users>
            <!-- Admin user configured via environment variables -->
            <admin>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
                <access_management>1</access_management>
            </admin>
            
            <!-- ETL service user -->
            <etl_user>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <profile>etl_batch</profile>
                <quota>default</quota>
                <access_management>0</access_management>
                <databases>
                    <gflow>
                        <query>1</query>
                        <insert>1</insert>
                        <create_table>1</create_table>
                        <drop_table>1</drop_table>
                    </gflow>
                </databases>
            </etl_user>
        </users>
    </clickhouse>
---