apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: clickhouse
  labels:
    app: clickhouse
    component: database
    service-type: internal
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
  - name: http
    port: 8123
    targetPort: 8123
    protocol: TCP
  - name: native
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: interserver
    port: 9009
    targetPort: 9009
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-external
  namespace: clickhouse
  labels:
    app: clickhouse
    component: database
    service-type: external
spec:
  type: NodePort
  selector:
    app: clickhouse
  ports:
  - name: http
    port: 8123
    targetPort: 8123
    nodePort: 30123  # External access for admin/monitoring
    protocol: TCP
  - name: native
    port: 9000
    targetPort: 9000
    nodePort: 30900  # External access for native protocol
    protocol: TCP
---
# Headless service for StatefulSet compatibility (future clustering)
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-headless
  namespace: clickhouse
  labels:
    app: clickhouse
    component: database
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: clickhouse
  ports:
  - name: http
    port: 8123
    targetPort: 8123
    protocol: TCP
  - name: native
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: interserver
    port: 9009
    targetPort: 9009
    protocol: TCP
---