apiVersion: apps/v1
kind: Deployment
metadata:
  name: gflow-etl
  labels:
    app: gflow-etl
    component: streaming-etl
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gflow-etl
  template:
    metadata:
      labels:
        app: gflow-etl
        component: streaming-etl
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: gflow-etl
        image: justscroll/gflow-etl:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        env:
        # Kafka Configuration
        - name: GFLOW_KAFKA_BROKERS
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: GFLOW_KAFKA_CONSUMER_GROUP
          value: "gflow-etl-prod"
        - name: GFLOW_KAFKA_BATCH_SIZE
          value: "5000"
        
        # ClickHouse Configuration - using existing cluster secret
        - name: GFLOW_CLICKHOUSE_HOST
          valueFrom:
            secretKeyRef:
              name: clickhouse-credentials
              key: host
        - name: GFLOW_CLICKHOUSE_PORT
          valueFrom:
            secretKeyRef:
              name: clickhouse-credentials
              key: native-port
        - name: GFLOW_CLICKHOUSE_DATABASE
          valueFrom:
            secretKeyRef:
              name: clickhouse-credentials
              key: database
        - name: GFLOW_CLICKHOUSE_USERNAME
          valueFrom:
            secretKeyRef:
              name: clickhouse-credentials
              key: username
        - name: GFLOW_CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-credentials
              key: password
        - name: GFLOW_CLICKHOUSE_TLS
          value: "false"
        - name: GFLOW_CLICKHOUSE_BATCH_SIZE
          value: "50000"
        - name: GFLOW_CLICKHOUSE_MAX_RETRIES
          value: "5"
        
        # Redis Configuration - using existing cluster service
        - name: GFLOW_REDIS_HOST
          value: "redis.redis.svc.cluster.local"
        - name: GFLOW_REDIS_PORT
          value: "6379"
        - name: GFLOW_REDIS_DATABASE
          value: "0"
        - name: GFLOW_REDIS_POOL_SIZE
          value: "20"
        
        # Demo and Monitoring
        - name: GFLOW_DEMO_ENABLED
          value: "true"
        - name: GFLOW_DEMO_DATA_RATE
          value: "500"
        - name: GFLOW_MONITORING_LOG_LEVEL
          value: "info"
        - name: GFLOW_MONITORING_ENABLED
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /etc/gflow-etl
          readOnly: true
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: config
        configMap:
          name: gflow-etl-config
---
apiVersion: v1
kind: Service
metadata:
  name: gflow-etl
  labels:
    app: gflow-etl
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    nodePort: 30092
    protocol: TCP
    name: metrics
  selector:
    app: gflow-etl
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gflow-etl-config
data:
  gflow-etl.yaml: |
    server:
      port: 8080
      read_timeout: 30s
      write_timeout: 30s
    
    kafka:
      brokers:
        - kafka.kafka.svc.cluster.local:9092
      consumer_group: gflow-etl-prod
      batch_size: 5000
      flush_interval: 5s
    
    clickhouse:
      # Host, port, database, username, password are provided via environment variables from Secret
      # See deployment environment variables section for actual configuration
      tls: false
      batch_size: 50000
      flush_timeout: 10s
      max_retries: 5
    
    redis:
      host: redis.redis.svc.cluster.local
      port: 6379
      database: 0
      pool_size: 20
    
    demo:
      enabled: true
      generate_data: true
      data_rate: 500
      generate_users: 1000
      session_window: 1h
      duplicate_ratio: 0.1
    
    monitoring:
      enabled: true
      metrics_port: 9090
      log_level: info
---
# Note: The clickhouse-credentials secret should be copied from the clickhouse namespace
# using the command mentioned in the header comments above