apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
  labels:
    app: redis
data:
  redis.conf: |
    # Redis configuration for small instance
    
    # Memory management
    maxmemory 768mb
    maxmemory-policy allkeys-lru
    
    # Persistence
    save 900 1
    save 300 10  
    save 60 10000
    appendonly yes
    appendfsync everysec
    
    # Network
    bind 0.0.0.0
    port 6379
    tcp-keepalive 300
    
    # Logging
    loglevel notice
    
    # Security (basic)
    protected-mode no
    
    # Performance tuning for small instance
    tcp-backlog 511
    databases 16
    
    # Disable some features to save memory
    rdbcompression yes
    rdbchecksum yes