name: Build and Push Utility Service

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      
      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          
      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      
      - name: Generate protobuf & test
        run: |
          protoc --go_out=. --go_opt=paths=source_relative \
                 --go-grpc_out=. --go-grpc_opt=paths=source_relative \
                 proto/hello.proto
          go test -v ./...
      
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and Push Docker Image
        if: github.event_name != 'pull_request'
        run: |
          docker build -t justscroll/utilitysvc:latest .
          docker push justscroll/utilitysvc:latest
